from __future__ import annotations

"""Compatibility export layer for legacy manifest/module references.

The implementation has been split into focused action modules, but the
manifest and some imports still point at ``atomic_actions``. Re-export the
public action callables here to preserve runtime compatibility while keeping
the real code organized by dependency cluster.
"""

from ..services.ocr_service import MultiOcrResult, OcrResult
from ..services.vision_service import MatchResult, MultiMatchResult
from .data_actions import (
    assert_condition,
    log,
    math_compute,
    regex_search,
    set_variable,
    stop_task,
    string_format,
    string_join,
    string_split,
)
from .input_actions import (
    click,
    double_click,
    drag,
    get_pixel_color,
    key_down,
    key_up,
    look_delta,
    look_direction,
    look_hold,
    look_sweep_horizontal,
    mouse_down,
    mouse_move_relative,
    mouse_up,
    move_to,
    press_hotkey,
    press_key,
    right_click,
    scroll,
    type_text,
)
from .interaction_actions import (
    drag_to_find,
    find_image_and_click,
    find_text_and_click,
    scan_and_find_best_match,
)
from .ocr_actions import (
    assert_text_equals,
    assert_text_exists,
    assert_text_not_exists,
    check_text_exists,
    find_text,
    get_text_in_region,
    preload_ocr,
    recognize_all_text,
)
from .process_actions import (
    get_process_status,
    start_process,
    stop_process,
    wait_for_process_exit,
)
from .system_actions import (
    file_read,
    file_write,
    focus_window,
    focus_window_with_input,
    get_window_size,
    publish_event,
)
from .task_actions import run_task
from .template_actions import (
    list_capture_backends,
    list_template_libraries,
    register_template_library,
    screen_selfcheck,
    set_capture_backend,
    unregister_template_library,
)
from .vision_actions import (
    assert_all_templates_in_set,
    assert_any_template_in_set,
    assert_image_exists,
    assert_image_not_exists,
    check_image_exists,
    find_all_images,
    find_all_templates_in_set,
    find_best_image,
    find_best_template_in_set,
    find_image,
    find_image_in_scrolling_area,
    find_templates_in_set,
    find_unique_template_in_set,
    list_templates_in_set,
)
from .wait_actions import (
    sleep,
    wait_for_any_template_in_set,
    wait_for_image,
    wait_for_templates_in_set_to_disappear,
    wait_for_text,
    wait_for_text_to_disappear,
)

__all__ = [
    "MatchResult",
    "MultiMatchResult",
    "MultiOcrResult",
    "OcrResult",
    "assert_all_templates_in_set",
    "assert_any_template_in_set",
    "assert_condition",
    "assert_image_exists",
    "assert_image_not_exists",
    "assert_text_equals",
    "assert_text_exists",
    "assert_text_not_exists",
    "check_image_exists",
    "check_text_exists",
    "click",
    "double_click",
    "drag",
    "drag_to_find",
    "file_read",
    "file_write",
    "find_all_images",
    "find_all_templates_in_set",
    "find_best_image",
    "find_best_template_in_set",
    "find_image",
    "find_image_and_click",
    "find_image_in_scrolling_area",
    "find_templates_in_set",
    "find_text",
    "find_text_and_click",
    "find_unique_template_in_set",
    "focus_window",
    "focus_window_with_input",
    "get_pixel_color",
    "get_process_status",
    "get_text_in_region",
    "get_window_size",
    "key_down",
    "key_up",
    "list_capture_backends",
    "list_template_libraries",
    "list_templates_in_set",
    "log",
    "math_compute",
    "mouse_down",
    "mouse_move_relative",
    "mouse_up",
    "move_to",
    "preload_ocr",
    "press_hotkey",
    "press_key",
    "publish_event",
    "recognize_all_text",
    "register_template_library",
    "regex_search",
    "right_click",
    "run_task",
    "scan_and_find_best_match",
    "screen_selfcheck",
    "scroll",
    "set_capture_backend",
    "set_variable",
    "sleep",
    "start_process",
    "stop_process",
    "stop_task",
    "string_format",
    "string_join",
    "string_split",
    "type_text",
    "unregister_template_library",
    "wait_for_any_template_in_set",
    "wait_for_image",
    "wait_for_process_exit",
    "wait_for_templates_in_set_to_disappear",
    "wait_for_text",
    "wait_for_text_to_disappear",
]
